# @package _global_

seed: 1000
dataset_repo_id: lerobot/koch_pick_place_lego

training:
#  offline_steps: 80000
  offline_steps: 1000
  online_steps: 0
  eval_freq: -1
#  save_freq: 10000
#  log_freq: 100
  save_freq: 100
  log_freq: 10
  save_checkpoint: true

  num_workers: 4

  batch_size: 180
#  lr: 1e-5
  lr_max: 1e-4
  warmup_steps: 5
  weight_decay: 1e-4
#  weight_decay: 1e-4
  grad_clip_norm: 10
  online_steps_between_rollouts: 1

  delta_timestamps:
    observation.images.phone: "[i / ${fps} for i in range(${policy.chunk_size})]"
    observation.images.laptop: "[i / ${fps} for i in range(${policy.chunk_size})]"
    observation.state: "[i / ${fps} for i in range(${policy.chunk_size})]"
    action: "[i / ${fps} for i in range(${policy.chunk_size})]"

#eval:
#  n_episodes: 50
#  batch_size: 50

# See `configuration_florence_pi0.py` for more details.
policy:
  name: florence_pi0

  chunk_size: 2
